services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_EXPRESS_API_BASE_URL=https://motionalgosim.xyz
    depends_on:
      - proxy
    networks:
      - app-network
    restart: always

  proxy:
    build:
      context: ./server
      dockerfile: proxy/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - EXPRESS_API_PORT=5000
      - FRONTEND_URL=https://motionalgosim.xyz:3000
      - PROXY_API_URL=http://proxy:5000/api
      - BACKEND_API_URL=http://backend:5001/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=wsg.py
    command: python3 wsg.py
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - frontend
    restart: always

networks:
  app-network:
    driver: bridge