version: '3.8'

services:
	frontend:
		build: ./client
		ports:
			- "3000:3000"
		environment:
			- REACT_APP_API_URL=http://proxy:5000
		depends_on:
			- proxy

	proxy:
		build: ./server/proxy
		ports:
			- "5000:5000"
		environment:
			- FLASK_BACKEND_URL=http://backend:5001
		depends_on:
			- backend
		networks:
			- app-network

  	backend:
		build: ./server
		ports:
			- "5001:5001"
		networks:
			- app-network

networks:
	app-network:
		driver: bridge